### ISSUE TITLE
Create Low-Fidelity Wireframe for all Pages (Mobile)

### ISSUE THREAD

**Issue by laamiri-kaoutar** [laamiri-kaoutar/VisitMorocco#13]
## Tasks:
- [x] Create Low-Fidelity Wireframe for Home Page (Mobile)
- [x] Create Low-Fidelity Wireframe for Destinations Page (Mobile)
- [x] Create Low-Fidelity Wireframe for Gastronomie Page (Mobile)
- [x] Create Low-Fidelity Wireframe for FAQ Page (Mobile)
